<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-17T13:08:28 GMT" name="HMH_Test.HMH_Test.apiTest" finished-at="2024-01-17T13:08:32 GMT" duration-ms="4717">
    <groups>
    </groups>
    <test started-at="2024-01-17T13:08:28 GMT" name="Command line test" finished-at="2024-01-17T13:08:32 GMT" duration-ms="4717">
      <class name="HMH_Test.HMH_Test.apiTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:HMH_Test.HMH_Test.apiTest@dbd940d]" started-at="2024-01-17T13:08:28 GMT" name="setup" finished-at="2024-01-17T13:08:28 GMT" duration-ms="800" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testFavQuote()[pri:0, instance:HMH_Test.HMH_Test.apiTest@dbd940d]" started-at="2024-01-17T13:08:28 GMT" name="testFavQuote" finished-at="2024-01-17T13:08:30 GMT" duration-ms="1758" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFavQuote -->
        <test-method signature="testInvalidAuthorization()[pri:0, instance:HMH_Test.HMH_Test.apiTest@dbd940d]" started-at="2024-01-17T13:08:30 GMT" name="testInvalidAuthorization" finished-at="2024-01-17T13:08:31 GMT" duration-ms="591" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [401] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [401] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at HMH_Test.HMH_Test.apiTest.testInvalidAuthorization(apiTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidAuthorization -->
        <test-method signature="testListQuotes()[pri:0, instance:HMH_Test.HMH_Test.apiTest@dbd940d]" started-at="2024-01-17T13:08:31 GMT" name="testListQuotes" finished-at="2024-01-17T13:08:32 GMT" duration-ms="1522" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testListQuotes -->
      </class> <!-- HMH_Test.HMH_Test.apiTest -->
    </test> <!-- Command line test -->
  </suite> <!-- HMH_Test.HMH_Test.apiTest -->
</testng-results>
